apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-time-deployment
  labels:
    app: node-time
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-time
  template:
    metadata:
      labels:
        app: node-time
    spec:
      containers:
      - name: node-time
        image: node-time:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 9000
        env:
          - name: TIME_API
            valueFrom:
              configMapKeyRef:
                name: time-config
                key: time_api
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: time-config
                key: port
          